### ISSUE TITLE
name of scaffolds

### ISSUE THREAD

**Issue by blaflamme** [Pylons/pyramid-cookiecutter-starter#1]
Just to raise the possible issue before everything is done and updated everywhere... since it's done using `cookie cutter` would it make more sense to name those scaffolds like `something-cookie` ?
- pyramid-starter-cookie
- pyramid-alchemy-cookie
- pyramid-zodb-cookie

**Comment by stevepiercy** [comment]
Carlos and I discussed the naming convention, and considered "cookiecutter" at the end of the names initially, but it made more sense to put it in the second "chunk" because:
- Most Pyramid add-ons start with "pyramid" as the first chunk.
- The second chunk is the specific add-on name, so it makes sense to extend the pattern to subsequent chunks, i.e., `pyramid-specific_chunk-specific_to_specific_chunk`.
- Bonus: all cookiecutters will group together when sorted alphabetically.

Also its name is "cookiecutter", no space, and not "cookie". We should respect the name, branding, and identity of that package.

**Comment by blaflamme** [comment]
It appears the way cookiecutters are named is mostly using the scheme `cookiecutter-something` when looking at the listing (I still prefer at the end), and the funny thing is they refer as `cookies` here and there when referring to those packages, and it make sense as Factory -> Product. I won't be surprised we'll see that naming raising up in the future, stay tuned.

**Comment by mmerickel** [comment]
It definitely seems the majority of cookiecutters linked on their home page start with `cookiecutter-`. That being said there's certainly many that don't as well. I'm happy with the current decision however.
