### ISSUE TITLE
__init__.py could use more guidance on structure

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid-cookiecutter-starter#19]
I would like to organize `__init__.py`'s `main`:

```
def main(...):
   init_includes()
   init_routing()
   # making room for more things like init_logging(), init_db(), etc
   return run...
```

What do you think? As written it's kind of without guidance.

**Comment by stevepiercy** [comment]
I think it adds an opinion of how a developer should code their project or arrange their code, which is contrary to a [core tenet of Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/designdefense.html#pyramid-provides-too-few-rails).

I think it's OK for the cookiecutters to lack guidance because it frees developers to add on or enhance a primitive example. Where guidance is necessary, there is [documentation](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/project.html#pyramid-cookiecutters). Maybe we add that link to all the READMEs instead?

**Comment by mikeckennedy** [comment]
Yeah, that makes sense. There is a fair amount of guidance in the folder structure already. What I was proposing here is just a little bit to give newer devs the insight to consider organizing it but not really much to impose on anyway.

So from this:

```
def main(global_config, **settings):
    """ This function returns a Pyramid WSGI application.
    """
    config = Configurator(settings=settings)
    config.include('pyramid_chameleon')
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.scan()
    return config.make_wsgi_app()
```

To this:

```
def main(global_config, **settings):
    """ This function returns a Pyramid WSGI application.
    """
    config = Configurator(settings=settings)
    init_includes(config)
    init_routing(config)
    return config.make_wsgi_app()

def init_includes(config):
    config.include('pyramid_chameleon')

def init_routing(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.scan()
```

That doesn't feel overly opinionated to me. But if you guys think it is, just say so and close it out. :)

**Comment by mmerickel** [comment]
This is not idiomatic if you compare it to the config that is done in the alchemy cookiecutter where config is split out into different modules using `config.include`. I think it'd need to be adapted to that pattern first to consider adding to the starter.

**Comment by mikeckennedy** [comment]
OK, I'll look at the alchemy version.
