### ISSUE TITLE
Add pytest-cookies to test scaffold generation

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid-cookiecutter-starter#2]
Opening for discussion, per https://twitter.com/pydanny/status/739818666213146624.

The package [pytest-cookies](https://github.com/hackebrot/pytest-cookies) would test whether a project is generated successfully.

Do we have any other tests, excluding those that come with the project generated from the scaffold?

I assume if we did use pytest-cookies, then we could configure Travis-CI and Appveyor (for Windows) to automate testing of the cookiecutters.

**Comment by mmerickel** [comment]
This is cool. I think this is something that serves a very very similar purpose to pyramid's current scaffold test runner here https://github.com/Pylons/pyramid/blob/master/pyramid/scaffolds/tests.py.

As we're discussing moving the scaffolds out of pyramid I think we are actually NOT discussing removing the binding between pyramid and the scaffolds. As such, I think we'd still want to add this support to the pyramid project itself, and not the individual scaffolds. This should make it easier to ensure the scaffolds conform to the current pyramid code prior to release. I could be wrong here but that's my first impression.

**Comment by stevepiercy** [comment]
To clarify, I suggest two groups of tests:
1. a project is generated successfully via cookiecutter
2. a project's tests

Item 1 would be done in a cookiecutter's repo. I'm not sure where to do item 2.

Should we run the tests in Pyramid or each cookiecutter?

Will we need to add branches to each cookiecutter to align with Pyramid's branches?

**Comment by mmerickel** [comment]
We need to avoid making a lot more work for ourselves (for me) by moving to cookiecutter. Unless we come up with the right tooling / scripts to make this seamless then it's going to be really difficult to work on.

I think that Pyramid's current process of being able to execute the scaffold's test suite against Pyramid is a very solid approach. This would be what I described earlier where Pyramid's main git repo had a way to ensure the scaffolds work with the unreleased source.

> To clarify, I suggest two groups of tests:
> 
> a project is generated successfully via cookiecutter
> a project's tests
> Item 1 would be done in a cookiecutter's repo. I'm not sure where to do item 2.

I don't really see this as an issue but if you want to add some CI to the scaffolds that's fine with me. Similarly something to execute the test suite when pushing to the scaffolds.

> Will we need to add branches to each cookiecutter to align with Pyramid's branches?

There will need to be some way to convey to users what version of Pyramid each cookiecutter supports. This would again be something that hopefully could be scriptable because otherwise we now have 3 more repositories I have to manually update when I release Pyramid. Please no.

**Comment by cguardia** [comment]
@mmerickel I can help with the scripting part to free you from ever having to do anything about the cookiecutters. Can you give me more details about how you would like this to work?

**Comment by mmerickel** [comment]
@cguardia The process right now is simply to run https://github.com/Pylons/pyramid/blob/f0f4a3081be10c94332e81ff59bea94ad6559316/tox.ini#L23-L51 prior to release.

```
tox -r -e py27-scaffolds,py33-scaffolds,py34-scaffolds,py35-scaffolds,pypy-scaffolds
```

This will install every scaffold into separate virtualenvs and run their tests. It's just enough to make sure the scaffold isn't completely broken but is a decent integration test that we should figure out a comparable method to install and test the official scaffolds.
