### ISSUE TITLE
cookie cutter not found

### ISSUE THREAD

**Issue by datatalking** [Pylons/pyramid-cookiecutter-starter#49]
Ok so I followed the instructions and tried
1. cloning the repo - nogo
2. copying the repo - wont run
3. copying a tutorial - no go

what format or function runs the code?
The instructions in your code seem to supposed additional code that needs to be on the terminal yet you forget that some of us are brand new and only follow instructions.

cookiecutter gh:Pylons/pyramid-cookiecutter-starter
bash: cookiecutter: command not found

cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter
-bash: cookiecutter: command not found

Please complete your tutorial as it doesn't run as noted, i'm eager to run a pyramid server as my instructor says it works but your code generates those errors when I try to run it.

**Comment by stevepiercy** [comment]
Did you install cookiecutter? It is a [requirement](https://github.com/Pylons/pyramid-cookiecutter-starter#requirements) that you must install in order to invoke the command.

Instructions to install cookiecutter are hyperlinked at the above link, but for convenience:
https://cookiecutter.readthedocs.io/en/latest/installation.html

See also:
https://github.com/mikeckennedy/python-for-entrepreneurs-course-demos/issues/30

**Comment by datatalking** [comment]
I did install and it said it's...

"Did you read my notes"?!?

I don't have any experience in running your code and I followed the instructions on your page and it generated those errors.

I am going thru the talk python tutorial and his screen shows zsh... is that required?

Why does your code require so many sub dependencies yet you don't state those in your notes or comments.

https://github.com/Pylons/pyramid-cookiecutter-starter
I followed these. It's since they were attached to the code, if readme docs are posted in two different places why are we doubling up on places where they are documented when github has the readme built in?

**Comment by stevepiercy** [comment]
> I did install and it said it's...
> "Did you read my notes"?!?

I don't understand this.

> his screen shows zsh... is that required?

No.

> Why does your code require so many sub dependencies yet you don't state those in your notes or comments.

To which subdependencies do your refer?

> https://github.com/Pylons/pyramid-cookiecutter-starter
> I followed these.

Since your shell cannot find cookiecutter, then you either did not install it or it is not in your path. What specific commands and procedure did you follow to install cookiecutter on your system?

> It's since they were attached to the code, if readme docs are posted in two different places why are we doubling up on places where they are documented when github has the readme built in?

What other place? This repo is for this project only, pyramid-cookiecutter-starter.

When reporting an issue, please refer to [Get Support](https://pylonsproject.org/community-support.html) and provide sufficient information to reproduce the issue.
